version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: vmm-controlplane/gen
plugins:
  - remote: buf.build/protocolbuffers/go
    out: gen
    opt: paths=source_relative
  - remote: buf.build/connectrpc/go
    out: gen
    opt: paths=source_relative
inputs:
  - directory: proto
