---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubernetes.unkey.com
  resources:
  - sentinels
  - unkeydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes.unkey.com
  resources:
  - sentinels/finalizers
  - unkeydeployments/finalizers
  verbs:
  - update
- apiGroups:
  - kubernetes.unkey.com
  resources:
  - sentinels/status
  - unkeydeployments/status
  verbs:
  - get
  - patch
  - update
