# This rule is not used by the project sentinelcontroller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kubernetes.unkey.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sentinelcontroller
    app.kubernetes.io/managed-by: kustomize
  name: sentinel-viewer-role
rules:
- apiGroups:
  - kubernetes.unkey.com
  resources:
  - sentinels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubernetes.unkey.com
  resources:
  - sentinels/status
  verbs:
  - get
