# This rule is not used by the project sentinelcontroller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the kubernetes.unkey.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sentinelcontroller
    app.kubernetes.io/managed-by: kustomize
  name: unkeydeployment-editor-role
rules:
- apiGroups:
  - kubernetes.unkey.com
  resources:
  - unkeydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubernetes.unkey.com
  resources:
  - unkeydeployments/status
  verbs:
  - get
