# This rule is not used by the project sentinelcontroller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over kubernetes.unkey.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sentinelcontroller
    app.kubernetes.io/managed-by: kustomize
  name: unkeydeployment-admin-role
rules:
- apiGroups:
  - kubernetes.unkey.com
  resources:
  - unkeydeployments
  verbs:
  - '*'
- apiGroups:
  - kubernetes.unkey.com
  resources:
  - unkeydeployments/status
  verbs:
  - get
