post:
  tags:
    - deploy
  summary: Complete upload
  description: |
    Signals that a deployment build context upload completed.

    **Authentication**: Requires a valid root key with appropriate permissions.
  operationId: deploy.completeUpload
  x-speakeasy-name-override: completeUpload
  security:
    - rootKey: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          "$ref": "./V2DeployCompleteUploadRequestBody.yaml"
  responses:
    "200":
      description: Upload completion accepted
      content:
        application/json:
          schema:
            "$ref": "./V2DeployCompleteUploadResponseBody.yaml"
    "400":
      description: Bad request
      content:
        application/json:
          schema:
            "$ref": "../../../../error/BadRequestErrorResponse.yaml"
    "401":
      description: Unauthorized
      content:
        application/json:
          schema:
            "$ref": "../../../../error/UnauthorizedErrorResponse.yaml"
    "403":
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "../../../../error/ForbiddenErrorResponse.yaml"
    "404":
      description: Not found
      content:
        application/json:
          schema:
            "$ref": "../../../../error/NotFoundErrorResponse.yaml"
    "500":
      description: Internal server error
      content:
        application/json:
          schema:
            "$ref": "../../../../error/InternalServerErrorResponse.yaml"
