apiVersion: v1
kind: Namespace
metadata:
  name: sentinels
---
apiVersion: v1
kind: Secret
metadata:
  name: database
  namespace: sentinels
type: Opaque
stringData:
  UNKEY_DATABASE_PRIMARY: "unkey:password@tcp(mysql.unkey.svc.cluster.local:3306)/unkey?parseTime=true&interpolateParams=true"
  UNKEY_DATABASE_REPLICA: "unkey:password@tcp(mysql.unkey.svc.cluster.local:3306)/unkey?parseTime=true&interpolateParams=true"
---
# Role allowing secret access in sentinels namespace - only bound to krane
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sentinel-secret-reader
  namespace: sentinels
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["database"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: krane-sentinel-secrets
  namespace: sentinels
subjects:
  - kind: ServiceAccount
    name: unkey-serviceaccount
    namespace: unkey
roleRef:
  kind: Role
  name: sentinel-secret-reader
  apiGroup: rbac.authorization.k8s.io
