# <docs-tag name="workflows-wrangler.toml">
#:schema node_modules/wrangler/config-schema.json
name = "workflows"
main = "src/index.ts"
compatibility_date = "2024-10-22"

compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.


[[workflows]]
# name of your workflow
name = "invoicing"
# binding name env.MYWORKFLOW
binding = "INVOICING"
# this is class that extends the Workflow class in src/index.ts
class_name = "Invoicing"
[triggers]
crons = ["0 13 1 * *"]
