instance_id = "ctrl-worker-dev"
region = "local"
default_domain = "unkey.local"
cname_domain = "unkey.local"
build_platform = "linux/amd64"
sentinel_image = "unkey/sentinel:latest"

[database]
primary = "unkey:password@tcp(mysql:3306)/unkey?parseTime=true&interpolateParams=true"

[vault]
url = "http://vault:8060"
token = "vault-test-token-123"

[otel]
enabled = false

[restate]
admin_url = "http://restate:9070"
http_port = 9080
register_as = "http://ctrl-worker:9080"

[registry]
url = "registry.depot.dev"
username = "x-token"
password = "${UNKEY_REGISTRY_PASSWORD}"

[depot]
api_url = "https://api.depot.dev"
project_region = "us-east-1"

[acme]
enabled = false

[clickhouse]
url = "clickhouse://default:password@clickhouse:9000?secure=false&skip_verify=true"
admin_url = "clickhouse://unkey_user_admin:C57RqT5EPZBqCJkMxN9mEZZEzMPcw9yBlwhIizk99t7kx6uLi9rYmtWObsXzdl@clickhouse:9000?secure=false&skip_verify=true"
