type: object
required:
  - uploadUrl
  - context
properties:
  uploadUrl:
    type: string
    description: Presigned PUT URL for uploading the build context tar file
    example: "https://s3.amazonaws.com/bucket/path?signature=..."
  context:
    type: string
    description: S3 path to use in the createDeployment request when building from source
    example: "proj_123abc/ctx_456def.tar.gz"
