version: "3.9"

services:
  unkey_api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=dev
    ports:
      - 8080:8080

    environment:
      DATABASE_DSN: "user:password@database/unkey"
      UNKEY_WORKSPACE_ID: "${UNKEY_WORKSPACE_ID}"
      UNKEY_API_ID: "${UNKEY_API_ID}"
      UNKEY_APP_AUTH_TOKEN: "${UNKEY_APP_AUTH_TOKEN}"
      UNKEY_KEY_AUTH_ID: "${UNKEY_KEY_AUTH_ID}"

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "unkey"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306

  database_bootstrap:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    depends_on:
      - database
    restart: "no"
    entrypoint: [ "bash", "-c", "go run ./tools/bootstrap"]
    environment:
      DATABASE_DSN: "user:password@database/unkey"
      UNKEY_WORKSPACE_ID: "${UNKEY_WORKSPACE_ID}"
      UNKEY_API_ID: "${UNKEY_API_ID}"
      UNKEY_APP_AUTH_TOKEN: "${UNKEY_APP_AUTH_TOKEN}"
      UNKEY_KEY_AUTH_ID: "${UNKEY_KEY_AUTH_ID}"
