# fly.toml app configuration file generated for unkey-api-preview on 2023-06-30T23:21:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "unkey-api-production"
primary_region = "iad"

[build]
  dockerfile = "./Dockerfile"

[deploy]
  strategy = "canary"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 35
  [http_service.concurrency]
    type = "requests"
    hard_limit = 1000
    soft_limit = 200

[checks]
  [checks.name_of_your_http_check]
    port = 8080
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/v1/liveness"

[restart]
  policy = "on-failure"
  max_retries = 5

[experimental]
cmd = [
  "/usr/local/bin/unkey",
  "agent",
   "--analytics=tinybird",
   "--event-bus=kafka",
   "--enable-axiom"
   ]
