# fly.toml app configuration file generated for unkey-api on 2023-06-12T23:17:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "unkey-global-api"
primary_region = "iad"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[http_service.concurrency]
  type = "requests"
  hard_limit = 1000
  soft_limit = 200


[deploy]
  strategy= "canary"

[checks]
  [checks.name_of_your_http_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/v1/liveness"
    port = 8080
    timeout = "10s"
    type = "http"
