name = "api"
main = "src/worker.ts"
compatibility_date = "2025-09-01"

compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false

## these are in local dev
[durable_objects]
bindings = [
  { name = "DO_RATELIMIT", class_name = "DurableObjectRatelimiter" },
  { name = "DO_USAGELIMIT", class_name = "DurableObjectUsagelimiter" },
]

[[migrations]]
tag = "v1"
new_classes = ["DurableObjectRatelimiter"]

[[migrations]]
tag = "v2"
new_classes = ["DurableObjectUsagelimiter"]

[[migrations]]
tag = "v3"
deleted_classes = ["DurableObjectRatelimiter"]


[[migrations]]
tag = "v4"
new_classes = ["DurableObjectRatelimiter"]


[env.development]
route = { pattern = "development-api.unkey.dev", custom_domain = true }
vars = { ENVIRONMENT = "development" }


[env.development.durable_objects]
bindings = [
  { name = "DO_RATELIMIT", class_name = "DurableObjectRatelimiter" },
  { name = "DO_USAGELIMIT", class_name = "DurableObjectUsagelimiter" },
]

[[unsafe.bindings]]
# The nameing scheme is important, because we're dynamically constructing
# these in the api code
#
# RL_{LIMIT}_{DURATION}s
#
# The namespace_id schema is somewhat made up though.
# I prefixed everything with 9900 -> 9900{limit}{duration}
name = "RL_10_60s"
type = "ratelimit"
namespace_id = "99001060"
simple = { limit = 10, period = 60 }

[[unsafe.bindings]]
name = "RL_30_60s"
type = "ratelimit"
namespace_id = "99003060"
simple = { limit = 30, period = 60 }

[[unsafe.bindings]]
name = "RL_50_60s"
type = "ratelimit"
namespace_id = "99005060"
simple = { limit = 50, period = 60 }


[[unsafe.bindings]]
name = "RL_200_60s"
type = "ratelimit"
namespace_id = "990020060"
simple = { limit = 200, period = 60 }


[[unsafe.bindings]]
name = "RL_600_60s"
type = "ratelimit"
namespace_id = "990060060"
simple = { limit = 600, period = 60 }


[[unsafe.bindings]]
name = "RL_1_10s"
type = "ratelimit"
namespace_id = "9900110"
simple = { limit = 1, period = 10 }


[[unsafe.bindings]]
name = "RL_500_10s"
type = "ratelimit"
namespace_id = "990050010"
simple = { limit = 500, period = 10 }

[[unsafe.bindings]]
name = "RL_200_10s"
type = "ratelimit"
namespace_id = "990020010"
simple = { limit = 200, period = 10 }


[queues]
consumers = [
  { queue = "key-migrations-development", max_batch_size = 10, max_retries = 10, dead_letter_queue = "key-migrations-development-dlq" },
  { queue = "key-migrations-development-dlq", max_batch_size = 10, max_retries = 10 },
]
producers = [
  { queue = "key-migrations-development", binding = "KEY_MIGRATIONS" },
]

[env.preview]
vars = { ENVIRONMENT = "preview", EMIT_METRICS_LOGS = "false", SYNC_RATELIMIT_ON_NO_DATA = "1" }
route = { pattern = "preview-api.unkey.dev", custom_domain = true }


[env.preview.durable_objects]
bindings = [
  { name = "DO_RATELIMIT", class_name = "DurableObjectRatelimiter" },
  { name = "DO_USAGELIMIT", class_name = "DurableObjectUsagelimiter" },

]
[env.preview.queues]
producers = [{ queue = "key-migrations-preview", binding = "KEY_MIGRATIONS" }]

consumers = [
  { queue = "key-migrations-preview", max_batch_size = 10, max_retries = 10, dead_letter_queue = "key-migrations-preview-dlq" },
  { queue = "key-migrations-preview-dlq", max_batch_size = 10, max_retries = 10 },
]

[[env.preview.unsafe.bindings]]
# The nameing scheme is important, because we're dynamically constructing
# these in the api code
#
# RL_{LIMIT}_{DURATION}s
#
# The namespace_id schema is somewhat made up though.
# I prefixed everything with 9900 -> 9900{limit}{duration}
name = "RL_10_60s"
type = "ratelimit"
namespace_id = "99001060"
simple = { limit = 10, period = 60 }

[[env.preview.unsafe.bindings]]
name = "RL_30_60s"
type = "ratelimit"
namespace_id = "99003060"
simple = { limit = 30, period = 60 }

[[env.preview.unsafe.bindings]]
name = "RL_50_60s"
type = "ratelimit"
namespace_id = "99005060"
simple = { limit = 50, period = 60 }


[[env.preview.unsafe.bindings]]
name = "RL_200_60s"
type = "ratelimit"
namespace_id = "990020060"
simple = { limit = 200, period = 60 }

[[env.preview.unsafe.bindings]]
name = "RL_600_60s"
type = "ratelimit"
namespace_id = "990060060"
simple = { limit = 600, period = 60 }


[[env.preview.unsafe.bindings]]
name = "RL_1_10s"
type = "ratelimit"
namespace_id = "9900110"
simple = { limit = 1, period = 10 }


[[env.preview.unsafe.bindings]]
name = "RL_500_10s"
type = "ratelimit"
namespace_id = "990050010"
simple = { limit = 500, period = 10 }

[[env.preview.unsafe.bindings]]
name = "RL_200_10s"
type = "ratelimit"
namespace_id = "990020010"
simple = { limit = 200, period = 10 }


# canary is a special environment that is used to test new code by a small percentage of users before it is rolled out to the rest of the world.
# all settings must be the same as production, except for the route pattern
[env.canary]
vars = { ENVIRONMENT = "canary", SYNC_RATELIMIT_ON_NO_DATA = "1" }
route = { pattern = "canary.unkey.dev", custom_domain = true }


[env.canary.durable_objects]
bindings = [
  { name = "DO_RATELIMIT", class_name = "DurableObjectRatelimiter" },
  { name = "DO_USAGELIMIT", class_name = "DurableObjectUsagelimiter" },
]

[env.canary.queues]
producers = [{ queue = "key-migrations-canary", binding = "KEY_MIGRATIONS" }]

consumers = [
  { queue = "key-migrations-canary", max_batch_size = 10, max_retries = 10, dead_letter_queue = "key-migrations-canary-dlq" },
  { queue = "key-migrations-canary-dlq", max_batch_size = 10, max_retries = 10 },
]

[[env.canary.unsafe.bindings]]
# The nameing scheme is important, because we're dynamically constructing
# these in the api code
#
# RL_{LIMIT}_{DURATION}s
#
# The namespace_id schema is somewhat made up though.
# I prefixed everything with 9900 -> 9900{limit}{duration}
name = "RL_10_60s"
type = "ratelimit"
namespace_id = "99001060"
simple = { limit = 10, period = 60 }

[[env.canary.unsafe.bindings]]
name = "RL_30_60s"
type = "ratelimit"
namespace_id = "99003060"
simple = { limit = 30, period = 60 }

[[env.canary.unsafe.bindings]]
name = "RL_50_60s"
type = "ratelimit"
namespace_id = "99005060"
simple = { limit = 50, period = 60 }


[[env.canary.unsafe.bindings]]
name = "RL_200_60s"
type = "ratelimit"
namespace_id = "990020060"
simple = { limit = 200, period = 60 }

[[env.canary.unsafe.bindings]]
name = "RL_600_60s"
type = "ratelimit"
namespace_id = "990060060"
simple = { limit = 600, period = 60 }


[[env.canary.unsafe.bindings]]
name = "RL_1_10s"
type = "ratelimit"
namespace_id = "9900110"
simple = { limit = 1, period = 10 }


[[env.canary.unsafe.bindings]]
name = "RL_500_10s"
type = "ratelimit"
namespace_id = "990050010"
simple = { limit = 500, period = 10 }

[[env.canary.unsafe.bindings]]
name = "RL_200_10s"
type = "ratelimit"
namespace_id = "990020010"
simple = { limit = 200, period = 10 }


[env.production]
vars = { ENVIRONMENT = "production", SYNC_RATELIMIT_ON_NO_DATA = "1" }
route = { pattern = "api.unkey.dev", custom_domain = true }
logpush = true


[env.production.durable_objects]
bindings = [
  { name = "DO_RATELIMIT", class_name = "DurableObjectRatelimiter" },
  { name = "DO_USAGELIMIT", class_name = "DurableObjectUsagelimiter" },
]

[env.production.queues]
producers = [
  { queue = "key-migrations-production", binding = "KEY_MIGRATIONS" },
]

consumers = [
  { queue = "key-migrations-production", max_batch_size = 10, max_retries = 10, dead_letter_queue = "key-migrations-production-dlq" },
  { queue = "key-migrations-production-dlq", max_batch_size = 10, max_retries = 10 },
]

[env.production.observability]
enabled = false

[[env.production.unsafe.bindings]]
# The nameing scheme is important, because we're dynamically constructing
# these in the api code
#
# RL_{LIMIT}_{DURATION}s
#
# The namespace_id schema is somewhat made up though.
# I prefixed everything with 9900 -> 9900{limit}{duration}
name = "RL_10_60s"
type = "ratelimit"
namespace_id = "99001060"
simple = { limit = 10, period = 60 }

[[env.production.unsafe.bindings]]
name = "RL_30_60s"
type = "ratelimit"
namespace_id = "99003060"
simple = { limit = 30, period = 60 }


[[env.production.unsafe.bindings]]
name = "RL_50_60s"
type = "ratelimit"
namespace_id = "99005060"
simple = { limit = 50, period = 60 }

[[env.production.unsafe.bindings]]
name = "RL_200_60s"
type = "ratelimit"
namespace_id = "990020060"
simple = { limit = 200, period = 60 }

[[env.production.unsafe.bindings]]
name = "RL_600_60s"
type = "ratelimit"
namespace_id = "990060060"
simple = { limit = 600, period = 60 }


[[env.production.unsafe.bindings]]
name = "RL_1_10s"
type = "ratelimit"
namespace_id = "9900110"
simple = { limit = 1, period = 10 }


[[env.production.unsafe.bindings]]
name = "RL_500_10s"
type = "ratelimit"
namespace_id = "990050010"
simple = { limit = 500, period = 10 }

[[env.production.unsafe.bindings]]
name = "RL_200_10s"
type = "ratelimit"
namespace_id = "990020010"
simple = { limit = 200, period = 10 }
