name = "api"
main = "src/worker.ts"
compatibility_date = "2023-11-06"


# [durable_objects]
# bindings = [
#   {name = "RATELIMIT", class_name = "Ratelimit"}
# ]

# [[migrations]]
# tag = "v1"
# new_classes = ["Ratelimit"]

[env.dev]
route = { pattern = "dev.api.unkey.app", custom_domain = true }


vars = {ENVIRONMENT = "dev"}

[env.preview]
vars = {  ENVIRONMENT = "preview"}
route = { pattern = "preview.api.unkey.app", custom_domain = true }


[env.production]
vars = {  ENVIRONMENT = "production"}
route = { pattern = "api.unkey.app", custom_domain = true }
