name: Artillery

concurrency: artillery

on:
  workflow_dispatch:
    inputs:
      baseUrl:
        required: true
        type: string

  workflow_call:
    inputs:
      baseUrl:
        required: true
        type: string

jobs:
  artillery:
    name: Artillery
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        region: [
            ap-east-1,
            ap-northeast-1,
            ap-northeast-2,
            ap-south-1,
            ap-southeast-1,
            ca-central-1,
            eu-west-1,
            eu-west-2,
            eu-west-3,
            me-south-1,
            sa-east-1
            us-west-2,
            ap-southeast-2,
            eu-central-1,
            us-west-1,
            us-east-2,
            us-east-1,
          ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create .env
        run: |
          echo "UNKEY_KEY=${{ secrets.UNKEY_KEY }}" >> .env
          echo "BASE_URL=${{inputs.baseUrl}}" >> .env

      - name: Test ${{matrix.region}}
        uses: artilleryio/action-cli@v1
        with:
          command: run-fargate --region ${{matrix.region}} ./tools/artillery/keys.verifyKey.yaml --record --dotenv ./.env --tags aws:fargate,region:${{matrix.region}} --target=${{inputs.baseUrl}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ARTILLERY_CLOUD_API_KEY: ${{secrets.ARTILLERY_CLOUD_KEY}}
