name: Build
on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run containers
        run: docker compose -f ./deployment/docker-compose.yaml up -d mysql planetscale

      - name: Install
        uses: ./.github/actions/install
        with:
          ts: true

      - name: Build
        run: pnpm turbo run build --filter=./apps/api



      - name: Create .dev.vars
        run: |
          cat <<EOF > .dev.vars
          DATABASE_HOST=localhost:3900
          DATABASE_USERNAME=unkey
          DATABASE_PASSWORD=password
          EOF
        working-directory: apps/api
      - name: Run worker
        run: pnpm dev & sleep 15
        working-directory: apps/api




      - name: Load Schema into MySQL
        run: pnpm drizzle-kit push
        working-directory: internal/db
        env:
          DRIZZLE_DATABASE_URL: "mysql://unkey:password@localhost:3306/unkey"



      - name: Build
        run: pnpm build
        env:
          DATABASE_HOST: localhost:8080
          DATABASE_USERNAME: unkey
          DATABASE_PASSWORD: password
          DATABASE_NAME: unkey
          UNKEY_WORKSPACE_ID: "not-empty"
          UNKEY_API_ID: "not-empty"
          UNKEY_WEBHOOK_KEYS_API_ID: "not-empty"
          AGENT_URL: "http://localhost:8080"
          AGENT_TOKEN: "not-empty"
          AUTH_PROVIDER: "workos"
          WORKOS_CLIENT_ID: "client_"
          WORKOS_API_KEY: "sk_test_"
          WORKOS_COOKIE_PASSWORD: "IAMACOOKIEPASSWORD"
          NEXT_PUBLIC_WORKOS_REDIRECT_URI: "http://localhost:3000/auth/sso-callback"
