name: Prune old images
permissions:
  contents: read
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day
jobs:
  clean:
    environment: operations
    runs-on: blacksmith-4vcpu-ubuntu-2404
    name: Delete old test images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: unkeyed
          token: ${{ secrets.PAT }}
          image-names: "unkey agent"
          image-tags: "!latest"
          keep-n-most-recent: 10
          cut-off: 4w
          dry-run: true
