name: Lint Go Code
on:
  workflow_call:
permissions:
  contents: read
jobs:
  golangci-lint:
    name: Lint
    runs-on: depot-ubuntu-24.04-4
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Setup Go
        uses: ./.github/actions/setup-go
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run golangci-lint
        run: |
          go tool golangci-lint run
        working-directory: go
