name: Test Logdrain
on:
  workflow_call:
permissions:
  contents: read
jobs:
  test:
    name: Test Logdrain
    runs-on: depot-ubuntu-24.04-4
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Wrangler
        uses: ./.github/actions/setup-wrangler
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Type Check
        run: npx tsc --noEmit
        working-directory: apps/logdrain
        env:
          CI: 1
      - name: Build Check
        run: wrangler deploy --dry-run
        working-directory: apps/logdrain
        env:
          CI: 1
