name: Unit Tests
on:
  workflow_call:
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: depot-ubuntu-24.04-4
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Setup Docker permissions
        run: |
          sudo chmod 666 /var/run/docker.sock
          docker version
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: pnpm turbo run build --filter='./internal/*'
        env:
          CI: 1
      - name: Test
        run: pnpm turbo run test --filter '!api'
        env:
          CI: 1
          TESTCONTAINERS_RYUK_DISABLED: true
          DOCKER_HOST: unix:///var/run/docker.sock
          TESTCONTAINERS_HOST_OVERRIDE: localhost
