name: Deploy API Enterprise
permissions:
  contents: read
on:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
        description: "Cloudflare API Token"
jobs:
  deploy:
    runs-on: depot-ubuntu-24.04-4
    environment: Enterprise
    strategy:
      fail-fast: true
      matrix:
        workers:
          [
            { name: "enterprise-default", domain: "enterprise.unkey.dev" },
            { name: "enterprise-fireworks", domain: "fireworks.unkey.dev" },
          ]
    name: Deploy ${{ matrix.workers.domain }}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Wrangler
        uses: ./.github/actions/setup-wrangler
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: pnpm turbo run build --filter='./apps/api'
        env:
          CI: 1
        working-directory: web
      - name: Configure worker
        run: |
          sed -i 's/__CUSTOM_NAME__/${{matrix.workers.name }}/g' ./wrangler.custom.toml
          sed -i 's/__CUSTOM_DOMAIN__/${{matrix.workers.domain}}/g' ./wrangler.custom.toml
        working-directory: web/apps/api
      - name: Deploy
        run: wrangler deploy --config=./wrangler.custom.toml --var VERSION:$(git rev-parse --short HEAD)
        working-directory: web/apps/api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
