name: Unit Tests
on:
  workflow_call:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        path:
          - "./internal/billing"
          - "./internal/encryption"
          - "./internal/hash"
          - "./internal/id"
          - "./internal/keys"
          - "./internal/resend"
          - "./internal/clickhouse"
          - "./packages/api"
          - "./packages/cache"
          - "./packages/hono"
          - "./packages/nextjs"
          - "./packages/rbac"
          - "./apps/dashboard"
    name: Test ${{matrix.path}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        uses: ./.github/actions/install
        with:
          ts: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        if: ${{ matrix.path != './apps/dashboard' }}
        run: pnpm turbo run build --filter=${{matrix.path}}
      - name: Test
        run: pnpm turbo run test --filter=${{matrix.path}}
